openapi: '3.1.0'
info:
  title: MyRecallAppClientApi
  version: 1.0.0
servers:
  - url: http://Rob-Work-M3.local:8080/api
    description: Rob-Work-M3 service
paths:
  /pjson:
    get:
      operationId: putJson
      parameters:
        - name: user
          required: false
          in: query
          description: The user of the topic.
          schema:
            type: string
        - name: topic
          required: false
          in: query
          description: The topic.
          schema:
            type: string
        - name: content
          required: false
          in: query
          description: The content of the topic.
          schema:
            type: string
      responses:
        '200':
          description: A success response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Json'
  /list:
    get:
      operationId: listTopics
      parameters:
      - name: user
        required: false
        in: query
        description: The owner of the topic.
        schema:
          type: string
      responses:
        '200':
          description: A success response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Json'
  /gjson:
    get:
      operationId: getJson
      parameters:
      - name: user
        required: false
        in: query
        description: The owner of the topic.
        schema:
          type: string
      - name: topic
        required: false
        in: query
        description: The topic name.
        schema:
          type: string
      responses:
        '200':
          description: A success response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Json'
components:
  schemas:
    Json:
      type: object
      description: A return value.
      properties:
        message:
          type: string
          description: The string representation of the result.
      required:
        - message
